### ISSUE TITLE
add: 新規会員登録完了ページの作成

### ISSUE THREAD

**Issue by KogaYamada** [KogaYamada/event-app#86]
## 概要
新規会員登録の完了したページのの作成。
## 詳細
* screensに作成してください。
* ファイル名はsignup-done.component.tsx
* 既存のコンポーネントを組み合わせて作成お願いします
* storybookに追加お願いします。（できれば）

## デザイン
https://xd.adobe.com/view/6c542d27-4132-45af-42f1-b62171b52558-1a65/screen/095f80ff-cb1d-4732-a553-df5d89aef820

**Comment by nozomi-iida** [comment]
やります。
